# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Daniel Öberg
description: >- # this means to ignore newlines until "baseurl:"
  Reflektioner om data science, funktionell programmering och 
  lagar och regler som gäller för att motverka penningtvätt, 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danieloberg.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: daniel_oberg
github_username:  danieloberg
linkedin_username: danielob

# Build settings
remote_theme: thiagorossener/jekflix-template
theme: jekflix
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Feed
    url: /feed.xml

# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true

language: "en"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# SASS
sass:
  style: compressed
